plugins {
    id 'com.android.application'
}

android {
    namespace 'com.will.quickrecord'
    compileSdk 35

    defaultConfig {
        applicationId 'com.will.quickrecord'
        minSdk 24
        targetSdk 35
        versionCode 8
        versionName '1.4.0'
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    def cameraxVersion = '1.5.3'
    implementation 'androidx.core:core:1.15.0'
    implementation 'androidx.lifecycle:lifecycle-runtime:2.8.7'
    implementation "androidx.camera:camera-core:${cameraxVersion}"
    implementation "androidx.camera:camera-camera2:${cameraxVersion}"
    implementation "androidx.camera:camera-lifecycle:${cameraxVersion}"
    implementation "androidx.camera:camera-video:${cameraxVersion}"
    implementation "androidx.camera:camera-view:${cameraxVersion}"
    implementation 'com.google.mlkit:text-recognition-chinese:16.0.1'

    testImplementation 'junit:junit:4.13.2'
}
